<?php

function getRealUserIp()
{
    switch (true) {
        case (!empty($_SERVER['HTTP_X_REAL_IP'])):
            return $_SERVER['HTTP_X_REAL_IP'];
        case (!empty($_SERVER['HTTP_CLIENT_IP'])):
            return $_SERVER['HTTP_CLIENT_IP'];
        case (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])):
            return $_SERVER['HTTP_X_FORWARDED_FOR'];
        default:
            return $_SERVER['REMOTE_ADDR'];
    }
}

function isBot()
{
    $bots = [
        "(BOT for JCE)",
        "01h4x.com",
        "360Spider",
        "404checker",
        "404enemy",
        "7Siters",
        "80legs",
        "A6-Indexer",
        "AHC/2.1",
        "AIBOT",
        "ALittle Client",
        "APIs-Google",
        "ASPSeek",
        "Abonti",
        "Aboundex",
        "Acunetix",
        "ADmantX",
        "AdsBot-Google",
        "Adsbot",
        "AfD-Verbotsverfahren",
        "AhrefsBot",
        "AiHitBot",
        "Aipbot",
        "Akkoma",
        "Alexibot",
        "AllSubmitter",
        "Alligator",
        "AlphaBot",
        "Amazonbot",
        "Anarchie",
        "Anarchy",
        "Anarchy99",
        "Ankit",
        "Anthill",
        "Anthropic",
        "Apache-HttpClient/5",
        "ApacheBench",
        "Apexoo",
        "Applebot",
        "AppEngine-Google",
        "ArchiveBot",
        "Arquivo-web-crawler",
        "Aspiegel",
        "Asterias",
        "Astute SRM",
        "Atomseobot",
        "Attach",
        "AwarioBot",
        "AwarioRssBot",
        "AwarioSmartBot",
        "Axios",
        "BBBike",
        "BDCbot",
        "BDFetch",
        "BLEXBot",
        "BTWebClient",
        "BackDoorBot",
        "BackStreet",
        "BackWeb",
        "Backlink-Ceck",
        "BacklinkCrawler",
        "Badass",
        "Baiduspider",
        "Bandit",
        "Barkrowler",
        "BatchFTP",
        "Battleztar Bazinga",
        "BazQuxBot",
        "BehloolBot",
        "BetaBot",
        "Bigfoot",
        "Bingbot",
        "Bitacle",
        "Bitlybot",
        "Black Hole",
        "BlackWidow",
        "Blackboard",
        "Blow",
        "BlowFish",
        "BoardReader",
        "Boardreader",
        "Bolt",
        "BotALot",
        "Brandprotect",
        "Brandwatch",
        "Buck",
        "Buddy",
        "BuiltBotTough",
        "BuiltWith",
        "Bullseye",
        "BunnySlippers",
        "Butterfly",
        "BuzzSumo",
        "Bytespider",
        "CATExplorador",
        "CCBot",
        "CODE87",
        "CSHttp",
        "Calculon",
        "CazoodleBot",
        "Cegbfeieh",
        "CensysInspect",
        "ChatGPT",
        "CHlooe",
        "CheTeam",
        "CheeseBot",
        "CherryPicker",
        "ChinaClaw",
        "Citoid",
        "Claritybot",
        "Claude-Web",
        "Cliqzbot",
        "Cloud mapping",
        "Cloudflare SpeedTest",
        "Coccocbot",
        "Cogentbot",
        "Cohere-ai",
        "Collector",
        "Com.plumanalytics",
        "CommonCrawler",
        "CommonCrawler Node",
        "Copier",
        "CopyRightCheck",
        "Copyscape",
        "Cosmos",
        "Craftbot",
        "Crawl.sogou.com",
        "Crawler.feedback",
        "Crawler4j",
        "Crawling at Home Project",
        "CrazyWebCrawler",
        "Crescent",
        "CriteoBot",
        "CrunchBot",
        "Curious",
        "Curl/7",
        "Custo",
        "CyotekWebCopy",
        "DBLBot",
        "DIIbot",
        "DSearch",
        "DTS Agent",
        "DataCha0s",
        "DataForSeoBot",
        "DatabaseDriverMysqli",
        "Demon",
        "Demandbase-bot",
        "Deusu",
        "Devil",
        "Diffbot",
        "Digincore",
        "DigitalPebble",
        "Dirbuster",
        "Disco",
        "Discobot",
        "Discoverybot",
        "Dispatch",
        "DittoSpyder",
        "Dlvr.it",
        "DnBCrawler-Analytics",
        "DnyzBot",
        "DomCopBot",
        "DomainAppender",
        "DomainCrawler",
        "DomainSigmaCrawler",
        "DomainStatsBot",
        "Domainsproject.org",
        "DotBot",
        "Dotbot",
        "Down/5",
        "Download Wonder",
        "Dragonfly",
        "Drip",
        "DuckDuckBot",
        "DuckDuckGo",
        "ECCP/1.0",
        "EMail Siphon",
        "EMail Wolf",
        "EasyDL",
        "Ebingbong",
        "Ecairn-Grabber",
        "Ecxi",
        "Embedly",
        "EirGrabber",
        "EroCrawler",
        "Ev-crawler",
        "Evil",
        "Exabot",
        "Express WebPictures",
        "ExtLinksBot",
        "Extractor",
        "ExtractorPro",
        "Extreme Picture Finder",
        "EyeNetIE",
        "Ezooms",
        "FDM",
        "FHscan",
        "FacebookBot",
        "FacebookScraper",
        "Feeder",
        "Feedfetcher-Google",
        "Feedly",
        "Feedbot",
        "FemtosearchBot",
        "Fimap",
        "Firefox/7.0",
        "FlashGet",
        "FlipboardProxy",
        "Flunky",
        "Foobot",
        "Freeuploader",
        "Friendica",
        "FrontPage",
        "Fuzz",
        "FyberSpider",
        "Fyrebot",
        "G-i-g-a-b-o-t",
        "GPTBot",
        "GT::WWW",
        "GalaxyBot",
        "GarlikCrawler",
        "Genieo",
        "GermCrawler",
        "GetRight",
        "GetWeb",
        "Getintent",
        "Gigabot",
        "GigablastOpenSource/1.0",
        "Giant Rhubarb",
        "Gluten Free Crawler",
        "Go!Zilla",
        "Go-Ahead-Got-It",
        "Go-http-client",
        "GoZilla",
        "Google Ad monitoring",
        "Google Producer",
        "Google-Apps-Scrip",
        "Google-Extended",
        "Google-InspectionTool",
        "Google-Safety",
        "GoogleOther",
        "Googlebot",
        "Gotit",
        "GrabNet",
        "Grabber",
        "Grafula",
        "GrapeFX",
        "GrapeshotCrawler",
        "GridBot",
        "GroupHigh",
        "Grokkit-crawler",
        "GuzzleHttp",
        "HEADMasterSEO",
        "HMView",
        "HTMLparser",
        "HTTP::Lite",
        "HTTP_Request2",
        "HTTrack",
        "Haansoft",
        "HaosouSpider",
        "Harvest",
        "Havij",
        "Heritrix",
        "Hloader",
        "HonoluluBot",
        "Humanlinks",
        "HybridBot",
        "IABot",
        "IDBTE4M",
        "IDBot",
        "IRLbot",
        "Iblog",
        "Id-search",
        "IlseBot",
        "Image Fetch",
        "Image Sucker",
        "ImageFetcher",
        "ImagesiftBot",
        "InAGist",
        "IndeedBot",
        "Indy Library",
        "InfoNaviRobot",
        "InfoTekies",
        "Instabid",
        "Intelliseek",
        "InterGET",
        "Internet Measurement",
        "Internet Ninja",
        "InternetSeer",
        "InternetVista monitor",
        "Ips-agent",
        "Iria",
        "Iskanie",
        "Isitwp.com",
        "IstellaBot",
        "Iubenda-radar",
        "JOC Web Spider",
        "JamesBOT",
        "Java/1.8",
        "Jbrofuzz",
        "JennyBot",
        "JetCar",
        "Jetty",
        "Jetslide",
        "JikeSpider",
        "Joomla",
        "Jorgee",
        "JustView",
        "Jyxobot",
        "KatBot",
        "Kenjin Spider",
        "Keybot Translation-Search-Machine",
        "Keys-so-bot",
        "Keyword Density",
        "Kinza",
        "Koyu.space",
        "Kozmosbot",
        "Kraken",
        "LCC",
        "LNSpiderguy",
        "LWP::Simple",
        "Lanshanbot",
        "Larbin",
        "Leap",
        "LeechFTP",
        "LeechGet",
        "LexiBot",
        "Lftp",
        "LibWeb",
        "Libwhisker",
        "Libwww-perl",
        "LieBaoFast",
        "Lightspeedsystems",
        "Likse",
        "LinkScan",
        "LinkWalker",
        "Linkbot",
        "Linkdex",
        "Linkdexbot",
        "LinkextractorPro",
        "Linkfluence.com",
        "LinkpadBot",
        "LinksManager",
        "LinqiaMetadataDownloaderBot",
        "LinqiaRSSBot",
        "LinqiaScrapeBot",
        "Lipperhey",
        "Lipperhey Spider",
        "Litemage_walker",
        "LivelapBot",
        "Lmspider",
        "LinkedInBot",
        "Ltx71",
        "Lwp-request",
        "Lwp-trivial",
        "MFC_Tear_Sample",
        "MIDown tool",
        "MIIxpc",
        "MJ12bot",
        "MQQBrowser",
        "MSFrontPage",
        "MSIECrawler",
        "MTRobot",
        "Mag-Net",
        "Magnet",
        "Magpie-crawler",
        "Mail.RU_Bot",
        "Majestic SEO",
        "Majestic-SEO",
        "Majestic12",
        "MarkMonitor",
        "MarkWatch",
        "Mass Downloader",
        "Masscan",
        "Mastodon",
        "Mata Hari",
        "MauiBot",
        "MaxPointCrawler",
        "Mb2345Browser",
        "MeanPath Bot",
        "Meanpathbot",
        "Mediapartners-Google",
        "Mediatoolkitbot",
        "Mediawords",
        "MegaIndex",
        "MetaInspector",
        "MetaJobBot",
        "MetadataScraper",
        "Meta-externalagent",
        "Metauri",
        "MicroMessenger",
        "Microsoft Data Access",
        "Microsoft Office",
        "Microsoft URL Control",
        "Minefield",
        "Miniflux",
        "Mister PiX",
        "Mjukisbyxor",
        "Moblie Safari",
        "Mojeek",
        "Mojolicious",
        "MolokaiBot",
        "Monitoring-plugins",
        "Morfeus Fucking Scanner",
        "Mozlila",
        "Mr.4x3",
        "Msrabot",
        "MuckRack",
        "Muhstik-scan",
        "Musobot",
        "NICErsPRO",
        "NING",
        "NPbot",
        "Name Intelligence",
        "Nameprotect",
        "Navroad",
        "NearSite",
        "Needle",
        "Neevabot",
        "Nessus",
        "NetAnts",
        "NetLyzer",
        "NetMechanic",
        "NetNewsWire",
        "NetSeer crawler",
        "NetSpider",
        "NetVIP",
        "NetZIP",
        "NetaceaBot",
        "Netcraft",
        "NetEstate NE Crawler",
        "Nettrack",
        "Netvibes",
        "NetworkingExtension",
        "NextGenSearchBot",
        "Nibbler",
        "Niki-Bot",
        "Niki-bot",
        "Nikto",
        "NimbleCrawler",
        "Nimbostratus",
        "Ninja",
        "Nmap",
        "Node-fetch",
        "Nuclei",
        "Nutch",
        "Nuzzel",
        "OAI-SearchBot",
        "OBot",
        "Octopus",
        "Offline Explorer",
        "Offline Navigator",
        "Okhttp",
        "Omgili",
        "Omigili",
        "OnCrawl",
        "OnalyticaBot",
        "OpenLinkProfiler",
        "OpenVAS",
        "Openfind",
        "Openvas",
        "OrangeBot",
        "OrangeSpider",
        "OutclicksBot",
        "OutfoxBot",
        "Ows.eu",
        "PECL::HTTP",
        "PHPCrawl",
        "PHP-Curl-Class",
        "POE-Component-Client-HTTP",
        "Pcore-HTTP",
        "Paqlebot",
        "Papa Foto",
        "PaperLiBot",
        "Pavuk",
        "PcBrowser",
        "PeoplePal",
        "PercolateCrawler",
        "PerplexityBot",
        "PetalBot",
        "Petalbot",
        "Petalsearch",
        "PhxBot",
        "Pi-Monster",
        "Picsearch",
        "Picscout",
        "PictureFinder",
        "Piepmatz",
        "Pimonster",
        "Pingdom",
        "Pinterest",
        "Pixray",
        "PleaseCrawl",
        "Pleroma",
        "PocketParser",
        "Pockey",
        "Polaris version",
        "ProPowerBot",
        "ProWebWalker",
        "Probe-image-size",
        "Probethenet",
        "Profound",
        "Protopage",
        "Proximic",
        "Psbot",
        "Pu_iN",
        "PulseCrawler",
        "Pump",
        "PxBroker",
        "PyCurl",
        "Python-requests",
        "Python-urllib",
        "Qwantbot",
        "Qwantify",
        "QueryN Metasearch",
        "QuerySeekerSpider",
        "Quick-Crawler",
        "R6_CommentReader",
        "R6_FeedFetcher",
        "RSSingBot",
        "RankActive",
        "RankActiveLinkBot",
        "RankFlex",
        "RankingBot",
        "RankingBot2",
        "Rankivabot",
        "RankurBot",
        "Re-Animator Bot",
        "Re-re",
        "ReGet",
        "RealDownload",
        "Reaper",
        "RebelMouse",
        "Recorder",
        "RedesScrapy",
        "Reeder",
        "RepoLookoutBot",
        "RepoMonkey",
        "Ripper",
        "RocketCrawler",
        "Rogerbot",
        "SBIder",
        "SEOkicks",
        "SEOlyticsCrawler",
        "SEOprofiler",
        "SEOstats",
        "SISTRIX",
        "SMTBot",
        "SWXCrawler",
        "SalesIntelligent",
        "Scan.lol",
        "ScanAlert",
        "Scanbot",
        "Scalaj-http",
        "Schmorp.de",
        "ScooperBot",
        "ScoutJet",
        "Scrapy",
        "Screaming",
        "ScreenerBot",
        "ScrepyBot",
        "Searchestate",
        "SearchmetricsBot",
        "Seekport",
        "Seekport Crawler",
        "Selfoss",
        "SemanticJuice",
        "SemanticScholarBot",
        "Semanticbot",
        "Semantic-visions.com",
        "Semrush",
        "SemrushBot",
        "SentiBot",
        "Seobility",
        "SeobilityBot",
        "Seocompany.store",
        "Seomoz",
        "Seoscanners",
        "SeoSiteCheckup",
        "Seostar",
        "SerendeputyBot",
        "Serpstatbot",
        "Sexsearcher",
        "SeznamBot",
        "SeznamBot/3.2",
        "SeznamHomepage",
        "Shodan",
        "ShowyouBot",
        "Siphon",
        "SiteCheck",
        "SiteCheckerBotCrawler",
        "SiteChecker.pro",
        "SiteExplorer",
        "SiteLockSpider",
        "SiteSnagger",
        "SiteSucker",
        "Sitebeam",
        "Siteimprove",
        "Siteripz",
        "Sitevigil",
        "Sleuth",
        "SlySearch",
        "SmartDownload",
        "Snake",
        "Snapbot",
        "Snoopy",
        "SocialRankIOBot",
        "Sociscraper",
        "Sogou",
        "Sogou web spider",
        "SogouSpider",
        "Sosospider",
        "Sottopop",
        "SpaceBison",
        "SpaceCowboys",
        "Spammen",
        "SpankBot",
        "Spanner",
        "SpiderLing",
        "SpiderWeb",
        "Spinn3r",
        "Spbot",
        "SputnikBot",
        "Sqlmap",
        "Sqlworm",
        "Sqworm",
        "Steeler",
        "StormCrawler",
        "StractBot",
        "Stripper",
        "Storebot-Google",
        "Sucker",
        "Sucuri",
        "SummalyBot",
        "SuperBot",
        "SuperHTTP",
        "Superfeedr",
        "Surfbot",
        "SurveyBot",
        "Suzuran",
        "Swiftbot",
        "Symfony BrowserKit",
        "Sysomos.com",
        "Sysscan",
        "Szukacz",
        "T0PHackTeam",
        "T8Abot",
        "TTD-Content",
        "TakeOut",
        "Teleport",
        "TeleportPro",
        "Telesoft",
        "Telesphoreo",
        "Telesphorep",
        "TencentTraveler",
        "Terrykyleseoagency.com",
        "The Intraformant",
        "The Knowledge AI",
        "TheNomad",
        "Thumbor",
        "TightTwatBot",
        "TinEye-bot-live",
        "Tiny Tiny RSS",
        "Titan",
        "Toata",
        "Toweyabot",
        "Tracemyfile",
        "Traackr.com",
        "Trendiction",
        "Trendiction.com",
        "Trendiction.de",
        "Trendictionbot",
        "TrendsmapResolver",
        "True_Robot",
        "Turingos",
        "Turnitin",
        "TurnitinBot",
        "TwengaBot",
        "Twice",
        "TweetedTimes Bot",
        "Tweetedtimes",
        "TweetmemeBot",
        "Twingly",
        "TwitterFeed",
        "Twitterbot",
        "Typhoeus",
        "URLy Warning",
        "URLy.Warning",
        "Ubermetrics",
        "Ubermetrics-technologies.com",
        "UnisterBot",
        "UnwindFetchor",
        "Upflow",
        "Updown_tester",
        "Urlresolver",
        "V-BOT",
        "VB Project",
        "VCI",
        "Vacuum",
        "Vagabondo",
        "VegeBot",
        "VelenPublicWebCrawler",
        "VelenPublicWebCrawler/1.0",
        "VeriCiteCrawler",
        "VidibleScraper",
        "Virusdie",
        "Voil",
        "VoidEYE",
        "Voltron",
        "Voyagerx.com",
        "WASALive-Bot",
        "WBSearchBot",
        "WEBDAV",
        "WISENutbot",
        "WPScan",
        "WWW-Collector-E",
        "WWW-Mechanize",
        "WWWOFFLE",
        "Wallpapers",
        "Wallpapers/3.0",
        "WallpapersHD",
        "WeSEE",
        "Web Auto",
        "WebBandit",
        "WebCollage",
        "WebCopier",
        "WebEnhancer",
        "WebFetch",
        "WebFuck",
        "WebGo IS",
        "WebImageCollector",
        "WebLeacher",
        "WebPix",
        "WebReaper",
        "WebSauger",
        "WebStripper",
        "WebSucker",
        "WebWhacker",
        "WebZIP",
        "Webalta",
        "Webdatastats.com",
        "WebmasterWorldForumBot",
        "Webshag",
        "WebsiteExtractor",
        "Website Quester",
        "Webster",
        "WellKnownBot",
        "Whack",
        "Whacker",
        "Whatweb",
        "Who.is Bot",
        "Widow",
        "WinHTTrack",
        "WiseGuys Robot",
        "Wonderbot",
        "Woobot",
        "WordPress.com mShots",
        "Wotbox",
        "Wprecon",
        "Xaldon WebSpider",
        "Xaldon_WebSpider",
        "XenForo",
        "Xenu",
        "XoviBot",
        "Y!J-BRW",
        "YaK/1.0",
        "Yahoo Ad monitoring",
        "Yahoo! Slurp",
        "YandexBot",
        "Yeti",
        "YisouSpider",
        "YoudaoBot",
        "Zade",
        "Zauba",
        "Zermelo",
        "Zeus",
        "Zitebot",
        "ZmEu",
        "ZoomBot",
        "ZoominfoBot",
        "ZumBot",
        "ZyBorg",
        "acebookexternalhit",
        "admantx-adform",
        "adscanner",
        "aiohttp",
        "arquivo.pt",
        "autoemailspider",
        "backlink-check",
        "baidu",
        "bingbot",
        "cah.io.community",
        "check1.exe",
        "clark-crawler",
        "coccocbot",
        "cognitiveseo",
        "commoncrawl",
        "cs.daum.net",
        "curl/7",
        "dataforseo.com",
        "domainappender",
        "domainsproject.org",
        "ecatch",
        "evc-batch",
        "facebookexternalhit",
        "facebookscraper",
        "feedbot",
        "genieo",
        "getstream.io/winds",
        "glutenfreepleasure.com",
        "gopher",
        "ia_archiver",
        "iaskspider",
        "ibwww-perl",
        "imagesift",
        "instabid",
        "internetVista monitor",
        "ips-agent",
        "isitwp.com",
        "iubenda-radar",
        "lwp-request",
        "lwp-trivial",
        "majestic12",
        "meanpathbot",
        "mediawords",
        "metadataparser",
        "metauri",
        "mon.itor.us",
        "muhstik-scan",
        "newspaper",
        "newsblur",
        "nutch",
        "obot",
        "okhttp",
        "page scorer",
        "pcbrowser",
        "plumanalytics",
        "polaris version",
        "probe-image-size",
        "profound",
        "proximic",
        "ripz",
        "rogerbot-crawler",
        "rss-is-dead",
        "s1z.ru",
        "satoristudio.net",
        "scan.lol",
        "schmorp.de",
        "seobility",
        "seocompany.store",
        "seoscanners",
        "seostar",
        "serpstatbot",
        "sexsearcher",
        "sindresorhus/got",
        "sitechecker.pro",
        "siteripz",
        "slackbot",
        "sogouspider",
        "sp_auditbot",
        "spbot",
        "spyfu",
        "sqlmap",
        "superfeedr",
        "sysscan",
        "takeout",
        "terrykyleseoagency.com",
        "trendiction.com",
        "trendiction.de",
        "tweetedtimes",
        "twingly",
        "ubermetrics-technologies.com",
        "updown_tester",
        "urlresolver",
        "voyagerx.com",
        "webdatastats.com",
        "webgains-bot",
        "webmeup-crawler",
        "webpros.com",
        "webprosbot",
        "whatsapp",
        "x09mozilla",
        "x22mozilla",
        "xpymep1.exe",
        "yacybot",
        "yahoo! slurp",
        "yahoo ad monitoring",
        "zauba.io",
        "zgrab",
        "zombiebot"
    ];
    $userAgent = isset($_SERVER['HTTP_USER_AGENT']) ? $_SERVER['HTTP_USER_AGENT'] : '';
    if ($userAgent === '')
        return false;

    foreach ($bots as $bot) {
        if (stripos($userAgent, $bot) !== false)
            return true;
    }
    return false;
}

function getUserAgent()
{
    return trim(string: isset($_SERVER['HTTP_USER_AGENT']) ? $_SERVER['HTTP_USER_AGENT'] : '');
}

function sourceTraductor(string $source): string
{
    $srcs = [
        'chatgpt' => 'ChatGPT',
        'google' => 'Google',
        'yahoo' => 'Yahoo',
        'bing' => 'Microsoft Bing',
        'carrot2' => 'Carrot2',
        'duckduckgo' => 'DuckDuckGo',
        'iseek' => 'iSeek',
        'qwant' => 'Qwant',
        'startpage' => 'Startpage',
        'base-search' => 'Base',
        'instagrok' => 'Instagrok',
        'openmd' => 'OpenMD',
        'refseek' => 'RefSeek',
        'researchgate' => 'ResearchGate',
        'baidu' => 'Baïdu',
        'yandex' => 'Yandex'
    ];

    foreach (array_keys($srcs) as $s) {
        if (stripos(strtolower($source), $s) !== false)
            return $srcs[$s];
    }

    return $source;
}

function browserTraductor(string $browser): string
{
    $srcs = [
        'opera' => 'Opera',
        'firefox' => 'Mozilla Firefox',
        'msie' => 'Microsoft Internet Explorer',
        'safari' => 'Apple Safari',
        'netscape' => 'Netscape',
        'edge' => 'Microsoft Edge',
        'trident' => 'Microsoft Internet Explorer',
        'chrome' => 'Google Chrome'
    ];

    foreach (array_keys($srcs) as $s) {
        if (stripos(strtolower($browser), $s) !== false) {
            $txt = $srcs[$s];
            $isMobile = stripos(strtolower($browser), 'mobile') !== false;
            $isAndroid = stripos(strtolower($browser), 'android') !== false;

            if ($isAndroid)
                $txt .= ' Android';
            if ($isMobile)
                $txt .= ' Mobile';

            return $txt;
        }
    }

    return $browser;
}

function platformTraductor(string $platform): string
{
    $srcs = [
        'win32' => 'Microsoft Windows (32 bits)',
        'win64' => 'Microsoft Windows (64 bits)',
        'win10' => 'Microsoft Windows (10)',
        'windows' => 'Microsoft Windows',
        'linux' => 'Linux',
        'macosx' => 'Apple Mac OS (X)',
        'mac os x' => 'Apple Mac OS (X)',
        'mac os' => 'Apple Mac OS',
        'macintosh' => 'Apple Mac OS'
    ];

    foreach (array_keys($srcs) as $s) {
        if (stripos(strtolower($platform), $s) !== false)
            return $srcs[$s];
    }

    return $platform;
}




if (!defined('MYIP_NORETURN')) {
    header("Content-Type: application/json; charset=utf-8");
    echo json_encode([
        'ip' => getRealUserIp(),
        'bot' => isBot(),
        'ua' => getUserAgent()
    ]);
}